# Generated by Django 3.2.7 on 2021-09-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sofia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundCallerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='intercom.action')),
            ],
            options={
                'verbose_name': 'Line bridge',
                'verbose_name_plural': 'Line bridges',
            },
            bases=('intercom.action',),
        ),
        migrations.CreateModel(
            name='OutboundExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('expression', models.CharField(max_length=50)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sofia.gateway')),
            ],
        ),
        migrations.CreateModel(
            name='Intercom',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
                ('default_outbound_caller_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercom.outboundcallerid')),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension_number', models.CharField(max_length=50)),
                ('voicemail', models.BooleanField(default=False)),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
            ],
            options={
                'verbose_name': 'Intercom extension',
                'verbose_name_plural': 'Intercom extensions',
            },
        ),
        migrations.CreateModel(
            name='DidExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_number', models.CharField(max_length=50, unique=True)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercom.extension')),
            ],
            options={
                'verbose_name': 'DID extension',
                'verbose_name_plural': 'DID extensions',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='extension',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intercom.extension'),
        ),
        migrations.CreateModel(
            name='OutsideLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sofia.gateway')),
                ('bridges', models.ManyToManyField(blank=True, to='intercom.Bridge')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('username', models.SlugField(unique=True)),
                ('password', models.CharField(max_length=50)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercom.extension')),
                ('intercom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercom.intercom')),
                ('outbound_caller_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intercom.outboundcallerid')),
                ('outbound_extensions', models.ManyToManyField(blank=True, to='intercom.OutboundExtension')),
                ('bridges', models.ManyToManyField(blank=True, to='intercom.Bridge')),
            ],
            options={
                'verbose_name': 'Intercom line',
                'verbose_name_plural': 'Intercom lines',
            },
        ),
        migrations.AddConstraint(
            model_name='extension',
            constraint=models.UniqueConstraint(fields=('extension_number', 'intercom'), name='intercom_extension_is_unique'),
        ),
    ]
