# Generated by Django 3.2.7 on 2021-09-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SofiaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(unique=True)),
                ('domain', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('sofiaprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sofia.sofiaprofile')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('proxy', models.CharField(max_length=50)),
                ('realm', models.CharField(max_length=50)),
                ('priority', models.PositiveSmallIntegerField()),
            ],
            bases=('sofia.sofiaprofile',),
        ),
        migrations.CreateModel(
            name='AclAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofia.gateway')),
            ],
            options={
                'verbose_name': 'ACL address',
                'verbose_name_plural': 'ACL addresses',
            },
        ),
    ]
